Generate Allure reports

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,7 +1,7 @@
 name: Playwright Tests
 
 on:
-  workflow_dispatch:  # Запуск по запросу
+  workflow_dispatch:  # Запуск вручную
 
 jobs:
   test:
@@ -17,8 +17,7 @@ jobs:
           node-version: 18  
 
       - name: Install dependencies
-        run: |
-          npm ci
+        run: npm ci
 
       - name: Install Playwright browsers
         run: npx playwright install --with-deps
@@ -26,19 +25,27 @@ jobs:
       - name: Install Java
         run: |
           sudo apt-get update
-          sudo apt-get install -y openjdk-11-jdk  # Установка Java 11
+          sudo apt-get install -y openjdk-11-jdk  # Установка Java для Allure
 
       - name: Install Allure Commandline
-        run: |
-          npm install -g allure-commandline --save-dev  # Установка Allure CLI
+        run: npm install -g allure-commandline --save-dev
 
       - name: Run Playwright tests
         run: npx playwright test --reporter=allure-playwright
+        continue-on-error: true  # Чтобы не прерывать workflow, если тесты упали
+
+      - name: Check if Allure results exist
+        run: |
+          if [ -d "allure-results" ] && [ "$(ls -A allure-results)" ]; then
+            echo "Allure results found."
+          else
+            echo "Allure results NOT found!"
+            exit 1
+          fi
 
       - name: Generate Allure report
-        run: |
-          npx allure generate allure-results --clean -o allure-report  # Генерация отчёта в одну и ту же папку
-        continue-on-error: true  # Добавляем это, чтобы не прерывать workflow, если шаг не удастся
+        run: npx allure generate allure-results --clean -o allure-report
+        continue-on-error: true  # Не прерывать workflow при ошибке
 
       - name: Commit updated report to gh-pages
         run: |
@@ -46,13 +53,13 @@ jobs:
           git config user.email "github-actions@github.com"
           git add allure-report/*
           git commit -m "Update Allure report"
-          git push origin gh-pages  # Коммитим новые данные в ветку gh-pages
-        continue-on-error: true  # Если этот шаг не удастся, workflow всё равно продолжится
+          git push origin gh-pages
+        continue-on-error: true  # Не прерывать workflow, если push не удался
 
       - name: Deploy Allure report to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
           branch: gh-pages
-          folder: allure-report  # Папка с отчётом
+          folder: allure-report
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
